### ISSUE TITLE
Stream Response Content not fixed on NETFX_CORE

### ISSUE THREAD

**Issue by Vangaorth** [ClaytonIndustries/HttpClient#1]
Fix on HttpBase.cs (done in commit b8885b1, 10 Aug 2017) for method `HandleByteArrayResponseRead(Action<HttpResponseMessage<byte[]>>, HttpCompletionOption, int)` should be applied also on the `NETFX_CORE` part, where the issue remains.

Being more precise, currently, rows 244 to 255 are:

    byte[] responseData = null;

    if (buffer.Length > contentReadThisRound)
    {
        responseData = new byte[contentReadThisRound];

        Array.Copy(buffer, responseData, contentReadThisRound);
    }
    else
    {
        responseData = buffer;
    }

but they should be:

    byte[] responseData = new byte[contentReadThisRound];

    Array.Copy(buffer, responseData, contentReadThisRound);

**Comment by ClaytonIndustries** [comment]
Thanks @Vangaorth , fixed as part of [2085aaf](https://github.com/ClaytonIndustries/HttpClient/commit/2085aafdd43a576d8fff2af605d279a9ba34aa0f)
