### ISSUE TITLE
Does it work on WebGL?

### ISSUE THREAD

**Issue by aleksey2403** [ClaytonIndustries/HttpClient#10]
Hi!

I used to work with this library on standalone, but now I test the code in WebGl and there seems to be no callbacks coming from request.
Here is the sample code:
`new HttpClient().Get(new Uri("https://github.com"), HttpCompletionOption.AllResponseContent, response =>
            {
                if (response.IsSuccessStatusCode){
Debug.Log("Success");
}
                else
                   {
Debug.Log("Fail");
}
            });`
I am not getting any single log in WebGL build, although on Standalone and iOS I get logs in console.
What do I miss?

**Comment by ClaytonIndustries** [comment]
Hi, unfortunately it doesn't work with WebGL
