### ISSUE TITLE
iPad OS 

### ISSUE THREAD

**Issue by FOKSlab** [ClaytonIndustries/HttpClient#12]
Hi,
Implementing HTTP client on my app on iOS solved some issues on UnityWebRequest on iOS but it seems to have an issue on iPadOS. 
My app is running perfectly on iOS 14.3 (iPhone 12 Pro Max) but trying it on iPadOS 14.2 & 14.3 (iPad Pro 11" 2020) I cannot read my remote file (same path tested on the 2 devices). Strange isn't it ? 

My code is the following, always getting the file content on iOS 14.3, never on iPad OS 14.3 where I always go into the _'else'_ section : 

```
    HttpClient _client = new HttpClient();
       string file2Load = "http://192.168.1.1/myDirectory/myFile.txt";
      Uri remotePath;
        try
        {
            remotePath = new Uri(file2Load);
        }
        catch (UriFormatException e)
        {
             // do something when error occurs
             return;
        }
        _client.Get(remotePath, HttpCompletionOption.AllResponseContent, r =>
        {
                if (r.HasContent)
                {

                    string fileContent = r.ReadAsString();

                    // do something with the content
                }
                else
                {
                   // cannot access the file / file is empty
                    return;
                }

        });

```
Maybe you could help me on this.
Regards

**Comment by ClaytonIndustries** [comment]
Hi, it may be that an exception is getting thrown. Check if r.Exception is set
