### ISSUE TITLE
About asynchronous network requests

### ISSUE THREAD

**Issue by leap233** [ClaytonIndustries/HttpClient#15]
What should I do if I want to wait for a request to execute successfully before continuing to run the following code instead of making a network request asynchronously?
For example, implement the following functions:
![image](https://user-images.githubusercontent.com/66467623/206124815-7a2db499-3a8b-4f3c-8d8e-22f1270723b4.png)

**Comment by claytonone** [comment]
Hi, if you are using a modern version of C# then you can write it as an async function and await it (example in the docs [here](https://github.com/ClaytonIndustries/HttpClient/wiki/Getting-Started#using-with-async--await))

**Comment by leap233** [comment]
> Hi, if you are using a modern version of C# then you can write it as an async function and await it (example in the docs [here](https://github.com/ClaytonIndustries/HttpClient/wiki/Getting-Started#using-with-async--await))

Thank you for your reply. I encountered some problems when using this example
Can you tell me which namespaces should be used for this example?
And I also encountered another problem: Uri could not be found, as shown below:

![image](https://user-images.githubusercontent.com/66467623/206651895-c31eb485-470b-4556-9c29-cb2b3e8134af.png)

![image](https://user-images.githubusercontent.com/66467623/206652228-3e000e37-afc3-4f63-b060-fea975453294.png)

**Comment by claytonone** [comment]
`using System;`
