### ISSUE TITLE
Adding Custom Headers

### ISSUE THREAD

**Issue by cmisztur** [ClaytonIndustries/HttpClient#2]
_client.CustomHeaders.Add(k,v) "Content-Type" fails with "This header must be modified with the appropiate property."

**Comment by ClaytonIndustries** [comment]
@cmisztur - by design, Content-Type is set automatically from the IHttpContent that you specify.

e.g new StringContent("Some data", Encoding.UTF8, "application/json";

**Comment by cmisztur** [comment]
Fair enough.  I have a workaround for your 'feature'.

Your asset will have its own provider in the next release of our asset.
https://assetstore.unity.com/packages/tools/network/web-api-kit-core-19663
