### ISSUE TITLE
ObjectDisposedException: The object was used after being disposed.

### ISSUE THREAD

**Issue by wanshichen716** [ClaytonIndustries/HttpClient#4]
I have a problem.

I use HttpClient.GetByteArray to download a file, after a moument call HttpClient.Abort().

> ObjectDisposedException: The object was used after being disposed.
System.Net.HttpWebResponse.CheckDisposed ()
System.Net.HttpWebResponse.get_StatusDescription ()
(wrapper remoting-invoke-with-check) System.Net.HttpWebResponse:get_StatusDescription ()
CI.HttpClient.Core.HttpBase+<RaiseResponseCallback>c__AnonStorey1`1[System.Byte[]].<>m__0 () (at Assets/HttpClient/HttpActions/HttpBase.cs:366)
CI.HttpClient.Core.Dispatcher.Update () (at Assets/HttpClient/Dispatcher/Dispatcher.cs:23)

I think this is a multithread problem.

See Dispatcher.cs

```
    public class Dispatcher : MonoBehaviour, IDispatcher
    {
        private static readonly Queue<Action> _queue = new Queue<Action>();
        private static readonly object _lock = new object();

        private void Awake()
        {
            DontDestroyOnLoad(gameObject);
        }

        public void Update()
        {
            lock (_lock)
            {
                while (_queue.Count > 0)
                {
                    _queue.Dequeue().Invoke();
                }
            }
        }

        public void Enqueue(Action action)
        {
            lock (_lock)
            {
                _queue.Enqueue(action);
            }
        }
    }
```

Enqueue() called in httpThread, Update() called in MainThread.
TimeLine:
>httpThread: Enqueue() 
MainThread: HttpClient.Abort()
MainThread: Update()  //throw ObjectDisposedException

**Comment by ClaytonIndustries** [comment]
Thanks for reporting, fixed in commit [f22750c](https://github.com/ClaytonIndustries/HttpClient/commit/f22750cd4dd02951a2a285812881d271ef42350e)
