### ISSUE TITLE
NullReferenceException on GetString

### ISSUE THREAD

**Issue by Vangaorth** [ClaytonIndustries/HttpClient#5]
When in editor (Unity 2017.4.4f1), Standalone platform or Android platform, below code produces a `NullReferenceException:`

    var httpClient = new HttpClient();
    httpClient.GetString(new Uri("https://api.github.com/users/mralexgray/repos"), (r) => {});

That should be located in `HttpBase.cs,` method `HandleStringResponseRead` :

    ...
    try 
    {
        _response = (HttpWebResponse)_request.GetResponse();
    }
    catch (WebException e)
    {
        _response = (HttpWebResponse)e.Response;
    }
    
    using (StreamReader streamReader = new StreamReader(_response.GetResponseStream()))
    ...

with a `Null` instance of `_response` returned by `_request.GetResponse()`.

Bug can be reproduced using the [following repository](https://github.com/Vangaorth/HttpClientIssue) (load the scene named `MainScene):`

**Comment by ClaytonIndustries** [comment]
Thanks for the report, fixed as of [4473f15](https://github.com/ClaytonIndustries/HttpClient/commit/4473f15fe5d75a31ae0de371102e97e7d71bde3f)
