### ISSUE TITLE
download mp3 file with stream 

### ISSUE THREAD

**Issue by ezzakyabdellah** [ClaytonIndustries/HttpClient#9]
when I download mp3 file with HttpCompletionOption.StreamResponseContent the output file get about 10kb like fraction of the download using stream or filestream ?
but HttpCompletionOption.AllResponseContent is working good without getting download progress

**Comment by ClaytonIndustries** [comment]
@MagicalScript - StreamResponseContent returns the response in chunks of 10k by default. You need to keep track of the data that is returned as the callback will be raised multiple times.
